# Generated by Django 5.1.3 on 2024-11-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(choices=[(True, 'Answered'), (False, 'Not answered')], default=False),
        ),
    ]
