# Generated by Django 5.1.3 on 2024-11-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_question_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
    ]
