# Generated by Django 5.1.3 on 2024-11-24 11:46

import CodeFlow.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_question_is_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='lecture_title',
        ),
        migrations.AddField(
            model_name='lecture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='title',
            field=models.CharField(default='title', max_length=100, validators=[django.core.validators.MinLengthValidator(5), CodeFlow.validators.TitleValidator()]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
