# Generated by Django 5.1.3 on 2024-11-24 15:25

import CodeFlow.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_rename_question_title_question_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=70, validators=[django.core.validators.MinLengthValidator(5), CodeFlow.validators.TitleValidator()])),
                ('text', models.TextField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.lecture')),
            ],
        ),
    ]
