# Generated by Django 5.1.3 on 2024-11-24 20:43

import CodeFlow.validators
import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[CodeFlow.validators.ImageSizeValidator(5)], verbose_name='image'),
        ),
    ]
